[authentication]
required = true

[authentication.legacy]
enabled = false
url = "https://login.minecraft.net"

[authentication.microsoft]
enabled = false
url = ""

[authentication.yggdrasil]
enabled = true
url = "https://authserver.mojang.com"

[minecraft]
max_players = -1
motd = "Hello from basalt.toml!"

[network]
bind = "0.0.0.0"
port = 25565

[whitelist]
enabled = false
list = [
	"cbpudding"
]
